export const messages = {
  es: {
    language: "Idioma", spanish: "Español", english: "Inglés",
    metadata: { title: "Reservas UMG", description: "Gestión de reservas de laboratorios UMG." },
    common: { retry: "Reintentar", loading: "Cargando información…", close: "Cerrar", cancel: "Cancelar", save: "Guardar cambios", active: "Activo", inactive: "Inactivo", unavailable: "No disponible" },
    pagination: { navigation: "Paginación", perPage: "Mostrar", previous: "Anterior", next: "Siguiente", page: "Página {page} de {total}", summary: "Mostrando {first}–{last} de {total}" },
    theme: { label: "Tema", light: "Claro", dark: "Nocturno", switchToLight: "Usar tema claro", switchToDark: "Usar tema nocturno" },
    navigation: { primary: "Principal", summary: "Resumen", availability: "Disponibilidad", reservations: "Reservas", administration: "Administración", logs: "Logs", profile: "Perfil" },
    loading: { route: "Cargando página…", session: "Comprobando tu sesión…", summary: "Cargando reservas…", administration: "Cargando administración…", logs: "Cargando registros…" },
    landing: { brand: "UMG · Ingeniería", eyebrow: "GESTIÓN ACADÉMICA", title: "Reserva el laboratorio que tu clase necesita.", description: "Consulta disponibilidad, confirma tu espacio y mantén tu agenda académica al día.", access: "Acceso institucional", spaces: "ESPACIOS DISPONIBLES", labsTitle: "Tres ambientes, un proceso claro.", labDescription: "Un espacio preparado para aprendizaje práctico y planificación docente.", labs: ["Cómputo y programación", "Redes y conectividad", "Desarrollo de proyectos"], processTitle: "Cómo reservar", process: [{ title: "Consulta", description: "Elige fecha y horario." }, { title: "Selecciona", description: "Encuentra un laboratorio libre." }, { title: "Confirma", description: "Registra el motivo de tu clase." }], faqTitle: "Preguntas frecuentes", faq: [{ question: "¿Quién puede solicitar una reserva?", answer: "Los usuarios institucionales autorizados pueden consultar y gestionar sus reservas." }, { question: "¿Dónde veo mi reserva?", answer: "El portal muestra las reservas publicadas por Render." }] },
    access: { back: "← UMG Ingeniería", title: "Iniciar sesión institucional", description: "Valida tus credenciales directamente con Render para entrar al portal.", username: "Correo institucional", password: "Contraseña", checking: "Verificando…", submit: "Iniciar sesión" },
    roles: { admin: "Administrador", professor: "Profesor" },
    auth: { signOut: "Cerrar sesión" },
    portal: { brand: "Reservas UMG", eyebrow: "Portal institucional", summaryTitle: "Resumen", summaryDescription: "Consulta la operación académica de tu cuenta institucional.", upcoming: "Próximas reservas", noReservations: "No hay reservas registradas.", checkAvailability: "Consultar disponibilidad" },
    profile: { eyebrow: "Cuenta institucional", title: "Mi perfil", description: "Consulta tu identidad activa y administra únicamente tu propia contraseña.", changePassword: "Cambiar contraseña", passwordDescription: "Esta acción se envía a Render para tu usuario actual.", newPassword: "Nueva contraseña", savePassword: "Actualizar contraseña", passwordUpdated: "Contraseña actualizada." },
    availability: { eyebrow: "Planificación", title: "Disponibilidad", description: "Busca laboratorios libres para el horario de tu clase.", date: "Fecha", start: "Hora de inicio", end: "Hora de fin", searching: "Consultando…", submit: "Buscar disponibilidad", empty: "No hay laboratorios disponibles para ese horario.", list: "Laboratorios disponibles", available: "Disponible", reserve: "Reservar este laboratorio" },
    reservations: { eyebrow: "Operación académica", title: "Reservas", description: "Consulta reservas de Render v1; cada rol ve únicamente las acciones que le corresponden.", filterLabel: "Filtrar reservas", filterLab: "Laboratorio para filtrar", filterDate: "Fecha para filtrar", filter: "Filtrar", listTitle: "Reservas publicadas", empty: "No hay reservas para los filtros seleccionados.", labFallback: "Laboratorio", noReason: "Sin motivo registrado", pending: "Pendiente", details: "Ver detalle", edit: "Modificar", cancel: "Cancelar", confirmCancel: "¿Cancelar esta reserva?", confirmCancelTitle: "Confirmar cancelación", detailTitle: "Detalle de reserva", closeDetail: "Cerrar detalle", createTitle: "Crear reserva", editTitle: "Modificar reserva", newReservation: "Nueva reserva", userId: "ID de usuario solicitante", lab: "Laboratorio", date: "Fecha", start: "Inicio", end: "Fin", reason: "Motivo", save: "Guardar cambios", confirm: "Confirmar reserva", cancelEdit: "Cancelar edición", created: "Reserva creada.", updated: "Reserva modificada.", cancelled: "Reserva cancelada." },
    admin: { eyebrow: "Operación institucional", title: "Administración", description: "Consulta los recursos publicados por Render; las acciones administrativas requieren rol de administrador.", labs: "Laboratorios", editLab: "Editar laboratorio", createLab: "Crear laboratorio", labName: "Nombre de laboratorio", status: "Estado", saveLab: "Guardar laboratorio", cancelEdit: "Cancelar edición", conditions: "Condiciones", editCondition: "Editar condición", createCondition: "Crear condición", lab: "Laboratorio", date: "Fecha", start: "Inicio", end: "Fin", type: "Tipo", reason: "Motivo", saveCondition: "Guardar condición", users: "Usuarios", createUser: "Crear usuario", email: "Correo institucional", password: "Contraseña", firstName: "Nombres", lastName: "Apellidos", roleId: "ID de rol", resetPassword: "Restablecer contraseña", resetPasswordFor: "Restablecer contraseña de {email}", temporaryPassword: "Contraseña temporal", saveTemporaryPassword: "Guardar contraseña temporal", deactivateUser: "Inactivar usuario", confirmDeactivate: "¿Inactivar a {email}?", confirmDeactivateTitle: "Confirmar inactivación", noRole: "Sin rol", audit: "Auditoría", auditUserId: "ID de usuario para auditoría", loadAudit: "Consultar auditoría", noAudit: "No hay registros de auditoría.", labCreated: "Laboratorio creado.", labUpdated: "Laboratorio actualizado.", conditionCreated: "Condición creada.", conditionUpdated: "Condición actualizada.", userCreated: "Usuario creado.", passwordUpdated: "Contraseña temporal establecida.", userDeactivated: "Usuario inactivado." },
    logs: { title: "Logs", eyebrow: "Trazabilidad", description: "Consulta los registros publicados por Render v1.", userId: "ID de usuario", load: "Consultar registros", requiredUserId: "Ingresa un ID de usuario para consultar los registros.", action: "Acción", module: "Módulo", descriptionLabel: "Descripción", date: "Fecha", empty: "No hay registros publicados.", total: "Registros", modules: "Módulos", topAction: "Acción principal", noActivity: "Sin actividad", byModule: "Actividad por módulo", byDate: "Actividad reciente", activityBand: "Banda de auditoría", activityTitle: "Pulso operativo", activityDescription: "Tendencia calculada con los registros devueltos por Render.", trendLabel: "Tendencia de actividad diaria", moduleChartLabel: "Distribución de actividad por módulo", metricsLabel: "Métricas de auditoría" },
    connection: { offline: "Sin conexión. Las reservas no se pueden modificar hasta reconectarte." },
    api: { validation: "Revisa los datos ingresados.", unauthorized: "No fue posible iniciar sesión.", forbidden: "No tienes acceso a esta acción.", notFound: "No encontramos la información solicitada.", conflict: "La acción entra en conflicto con el estado actual.", server: "El servicio no está disponible. Intenta nuevamente.", network: "Revisa tu conexión e inténtalo nuevamente." }
  },
  en: {
    language: "Language", spanish: "Spanish", english: "English",
    metadata: { title: "UMG Reservations", description: "UMG laboratory reservation management." },
    common: { retry: "Try again", loading: "Loading information…", close: "Close", cancel: "Cancel", save: "Save changes", active: "Active", inactive: "Inactive", unavailable: "Unavailable" },
    pagination: { navigation: "Pagination", perPage: "Show", previous: "Previous", next: "Next", page: "Page {page} of {total}", summary: "Showing {first}–{last} of {total}" },
    theme: { label: "Theme", light: "Light", dark: "Dark", switchToLight: "Use light theme", switchToDark: "Use dark theme" },
    navigation: { primary: "Primary", summary: "Summary", availability: "Availability", reservations: "Reservations", administration: "Administration", logs: "Logs", profile: "Profile" },
    loading: { route: "Loading page…", session: "Checking your session…", summary: "Loading reservations…", administration: "Loading administration…", logs: "Loading logs…" },
    landing: { brand: "UMG · Engineering", eyebrow: "ACADEMIC MANAGEMENT", title: "Reserve the laboratory your class needs.", description: "Check availability, confirm your space, and keep your academic schedule current.", access: "Institutional access", spaces: "AVAILABLE SPACES", labsTitle: "Three settings, one clear process.", labDescription: "A space prepared for practical learning and teaching planning.", labs: ["Computing and programming", "Networks and connectivity", "Project development"], processTitle: "How to reserve", process: [{ title: "Check", description: "Choose a date and time." }, { title: "Select", description: "Find an available laboratory." }, { title: "Confirm", description: "Record the reason for your class." }], faqTitle: "Frequently asked questions", faq: [{ question: "Who can request a reservation?", answer: "Authorized institutional users can check and manage their reservations." }, { question: "Where can I see my reservation?", answer: "The portal shows reservations published by Render." }] },
    access: { back: "← UMG Engineering", title: "Institutional sign in", description: "Validate your credentials directly with Render to enter the portal.", username: "Institutional email", password: "Password", checking: "Checking…", submit: "Sign in" },
    roles: { admin: "Administrator", professor: "Professor" },
    auth: { signOut: "Sign out" },
    portal: { brand: "UMG Reservations", eyebrow: "Institutional portal", summaryTitle: "Summary", summaryDescription: "Review the academic operations of your institutional account.", upcoming: "Upcoming reservations", noReservations: "There are no reservations registered.", checkAvailability: "Check availability" },
    profile: { eyebrow: "Institutional account", title: "My profile", description: "View your active identity and manage only your own password.", changePassword: "Change password", passwordDescription: "This action is sent to Render for your current user.", newPassword: "New password", savePassword: "Update password", passwordUpdated: "Password updated." },
    availability: { eyebrow: "Planning", title: "Availability", description: "Find free laboratories for your class schedule.", date: "Date", start: "Start time", end: "End time", searching: "Searching…", submit: "Search availability", empty: "No laboratories are available for that time.", list: "Available laboratories", available: "Available", reserve: "Reserve this laboratory" },
    reservations: { eyebrow: "Academic operations", title: "Reservations", description: "View Render v1 reservations; each role sees only its applicable actions.", filterLabel: "Filter reservations", filterLab: "Laboratory to filter", filterDate: "Date to filter", filter: "Filter", listTitle: "Published reservations", empty: "There are no reservations for the selected filters.", labFallback: "Laboratory", noReason: "No reason recorded", pending: "Pending", details: "View details", edit: "Edit", cancel: "Cancel", confirmCancel: "Cancel this reservation?", confirmCancelTitle: "Confirm cancellation", detailTitle: "Reservation details", closeDetail: "Close details", createTitle: "Create reservation", editTitle: "Edit reservation", newReservation: "New reservation", userId: "Requesting user ID", lab: "Laboratory", date: "Date", start: "Start", end: "End", reason: "Reason", save: "Save changes", confirm: "Confirm reservation", cancelEdit: "Cancel editing", created: "Reservation created.", updated: "Reservation updated.", cancelled: "Reservation cancelled." },
    admin: { eyebrow: "Institutional operations", title: "Administration", description: "Review resources published by Render; administrative actions require an administrator role.", labs: "Laboratories", editLab: "Edit laboratory", createLab: "Create laboratory", labName: "Laboratory name", status: "Status", saveLab: "Save laboratory", cancelEdit: "Cancel editing", conditions: "Conditions", editCondition: "Edit condition", createCondition: "Create condition", lab: "Laboratory", date: "Date", start: "Start", end: "End", type: "Type", reason: "Reason", saveCondition: "Save condition", users: "Users", createUser: "Create user", email: "Institutional email", password: "Password", firstName: "First names", lastName: "Last names", roleId: "Role ID", resetPassword: "Reset password", resetPasswordFor: "Reset password for {email}", temporaryPassword: "Temporary password", saveTemporaryPassword: "Save temporary password", deactivateUser: "Deactivate user", confirmDeactivate: "Deactivate {email}?", confirmDeactivateTitle: "Confirm deactivation", noRole: "No role", audit: "Audit", auditUserId: "User ID for audit", loadAudit: "Load audit", noAudit: "There are no audit records.", labCreated: "Laboratory created.", labUpdated: "Laboratory updated.", conditionCreated: "Condition created.", conditionUpdated: "Condition updated.", userCreated: "User created.", passwordUpdated: "Temporary password set.", userDeactivated: "User deactivated." },
    logs: { title: "Logs", eyebrow: "Traceability", description: "View records published by Render v1.", userId: "User ID", load: "Load records", requiredUserId: "Enter a user ID to load records.", action: "Action", module: "Module", descriptionLabel: "Description", date: "Date", empty: "There are no published logs.", total: "Records", modules: "Modules", topAction: "Top action", noActivity: "No activity", byModule: "Activity by module", byDate: "Recent activity", activityBand: "Audit band", activityTitle: "Operational pulse", activityDescription: "Trend calculated from records returned by Render.", trendLabel: "Daily activity trend", moduleChartLabel: "Activity distribution by module", metricsLabel: "Audit metrics" },
    connection: { offline: "You are offline. Reservations cannot be changed until you reconnect." },
    api: { validation: "Check the information entered.", unauthorized: "We could not sign you in.", forbidden: "You do not have access to this action.", notFound: "We could not find the requested information.", conflict: "This action conflicts with the current state.", server: "The service is unavailable. Please try again.", network: "Check your connection and try again." }
  }
};

export const textFor = (language, key) => key.split(".").reduce((value, part) => value?.[part], messages[language]) ?? key;
export const interpolate = (template, values = {}) => String(template).replace(/\{(\w+)\}/g, (_, key) => values[key] ?? `{${key}}`);
