openapi: 3.0.3
info:
  title: API UMG - Sistema de Reservas de Laboratorios
  version: 1.0.0
  description: API para gestionar reservas de laboratorios de la Facultad de Ingenieria
paths:
  /api/v2/auth/change-password/:
    post:
      operationId: auth_change_password_create
      tags:
      - auth
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Ejecutar change password
  /api/v2/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      security:
      - {}
      responses:
        '200':
          description: No response body
      summary: Iniciar sesion de api v2
  /api/v2/auth/logout/:
    post:
      operationId: auth_logout_create
      tags:
      - auth
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Ejecutar logout
  /api/v2/auth/me/:
    get:
      operationId: auth_me_retrieve
      tags:
      - auth
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Obtener me
  /api/v2/auth/refresh/:
    post:
      operationId: auth_refresh_create
      tags:
      - auth
      security:
      - {}
      responses:
        '200':
          description: No response body
      summary: Ejecutar refresh
  /api/v2/condiciones/:
    get:
      operationId: condiciones_retrieve
      tags:
      - condiciones
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Obtener conditions
    post:
      operationId: condiciones_create
      tags:
      - condiciones
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Ejecutar conditions
  /api/v2/condiciones/{id}/:
    put:
      operationId: condiciones_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - condiciones
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Actualizar condition
  /api/v2/labs/:
    get:
      operationId: labs_retrieve
      tags:
      - labs
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Obtener labs
    post:
      operationId: labs_create
      tags:
      - labs
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Ejecutar labs
  /api/v2/labs/{id}/:
    put:
      operationId: labs_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - labs
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Actualizar lab
  /api/v2/labs/disponibles/:
    get:
      operationId: labs_disponibles_retrieve
      tags:
      - labs
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Obtener available labs
  /api/v2/logs/:
    get:
      operationId: logs_retrieve
      tags:
      - logs
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Obtener logs
  /api/v2/reservas/:
    get:
      operationId: reservas_retrieve
      tags:
      - reservas
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Obtener reservations
    post:
      operationId: reservas_create
      tags:
      - reservas
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Ejecutar reservations
  /api/v2/reservas/{id}/:
    get:
      operationId: reservas_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - reservas
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Obtener reservation detail
  /api/v2/reservas/{id}/cancelar/:
    patch:
      operationId: reservas_cancelar_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - reservas
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Actualizar cancel reservation
  /api/v2/reservas/{id}/modificar/:
    put:
      operationId: reservas_modificar_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - reservas
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Actualizar reservation
  /api/v2/usuarios/:
    get:
      operationId: usuarios_retrieve
      tags:
      - usuarios
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Obtener users
    post:
      operationId: usuarios_create
      tags:
      - usuarios
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Ejecutar users
  /api/v2/usuarios/{id}/inactivar/:
    patch:
      operationId: usuarios_inactivar_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - usuarios
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Actualizar deactivate user
  /api/v2/usuarios/{id}/resetear-contrasena/:
    patch:
      operationId: usuarios_resetear_contrasena_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - usuarios
      security:
      - UMGJWT: []
      responses:
        '200':
          description: No response body
      summary: Actualizar reset user password
components:
  securitySchemes:
    UMGJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
