"use client";

import { useCallback, useEffect, useState } from "react";
import { createRenderApiClient } from "@/services/render-api";
import { StatusMessage } from "@/components/StatusMessage";
import { LoadingState } from "@/components/LoadingState";
import { useLanguage } from "@/components/LanguageProvider";
import { interpolate } from "@/lib/i18n";

const asList = (value) => Array.isArray(value) ? value : value ? [value] : [];
const field = (item, name) => item.raw?.[name] ?? item[name] ?? "";

export default function AdminPage() {
  const { t } = useLanguage();
  const [data, setData] = useState(null); const [error, setError] = useState(null); const [status, setStatus] = useState(null);
  const [editingLab, setEditingLab] = useState(null); const [editingCondition, setEditingCondition] = useState(null); const [resettingUser, setResettingUser] = useState(null);
  const fetchData = useCallback(async () => { const api = createRenderApiClient(); const results = await Promise.allSettled([api.listLabs(), api.listLabConditions(), api.listUsers(), api.listAuditLogs()]); const [labs, conditions, users, logs] = results.map((result) => result.status === "fulfilled" ? asList(result.value) : []); const failed = results.find((result) => result.status === "rejected"); return { value: { labs, conditions, users, logs }, error: failed?.reason?.code ?? null }; }, []);
  const load = useCallback(async () => { const next = await fetchData(); setData(next.value); setError(next.error); }, [fetchData]);
  useEffect(() => { let active = true; fetchData().then((next) => { if (active) { setData(next.value); setError(next.error); } }); return () => { active = false; }; }, [fetchData]);
  const run = async (work, success) => { setError(null); setStatus(null); try { await work(); setStatus(success); await load(); } catch (caught) { setError(caught?.code ?? "api.network"); } };
  if (!data) return <LoadingState messageKey="loading.administration" className="workflow-page" />;
  const submitLab = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = form.get("labName"); run(() => editingLab ? createRenderApiClient().updateLab({ id: editingLab.id, name, status: Number(form.get("labStatus")) }) : createRenderApiClient().createLab({ name }), editingLab ? "admin.labUpdated" : "admin.labCreated"); event.currentTarget.reset(); setEditingLab(null); };
  const conditionPayload = (form) => ({ labId: Number(form.get("conditionLabId")), date: form.get("conditionDate"), startTime: form.get("conditionStart"), endTime: form.get("conditionEnd"), type: form.get("conditionType"), reason: form.get("conditionReason"), status: Number(form.get("conditionStatus")) });
  const submitCondition = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = conditionPayload(form); const createPayload = Object.fromEntries(Object.entries(payload).filter(([key]) => key !== "status")); run(() => editingCondition ? createRenderApiClient().updateLabCondition({ id: editingCondition.id, ...payload }) : createRenderApiClient().createLabCondition(createPayload), editingCondition ? "admin.conditionUpdated" : "admin.conditionCreated"); event.currentTarget.reset(); setEditingCondition(null); };
  const submitUser = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => createRenderApiClient().createUser({ username: form.get("username"), password: form.get("password"), name: form.get("firstName"), lastName: form.get("lastName"), roleId: Number(form.get("roleId")) }), "admin.userCreated"); event.currentTarget.reset(); };
  const submitReset = (event) => { event.preventDefault(); const password = new FormData(event.currentTarget).get("temporaryPassword"); run(() => createRenderApiClient().resetUserPassword({ id: resettingUser.id, temporaryPassword: password }), "admin.passwordUpdated"); event.currentTarget.reset(); setResettingUser(null); };
  return <section className="workflow-page admin-page"><header className="page-heading"><p className="eyebrow">{t("admin.eyebrow")}</p><h1>{t("admin.title")}</h1><p>{t("admin.description")}</p></header>{error ? <StatusMessage code={error} onRetry={load} /> : null}{status ? <p role="status" className="success-message">{t(status)}</p> : null}
    <section className="data-panel" aria-labelledby="labs-title"><h2 id="labs-title">{t("admin.labs")}</h2><form onSubmit={submitLab} className="compact-form" key={editingLab?.id ?? "new-lab"}><h3>{t(editingLab ? "admin.editLab" : "admin.createLab")}</h3><label>{t("admin.labName")}<input name="labName" defaultValue={editingLab?.name ?? ""} required /></label>{editingLab ? <label>{t("admin.status")}<select name="labStatus" defaultValue={editingLab.status ?? 1}><option value="1">{t("common.active")}</option><option value="0">{t("common.inactive")}</option></select></label> : null}<div className="form-actions"><button className="button is-primary">{t(editingLab ? "admin.saveLab" : "admin.createLab")}</button>{editingLab ? <button type="button" className="button" onClick={() => setEditingLab(null)}>{t("admin.cancelEdit")}</button> : null}</div></form><ul className="record-list">{data.labs.map((lab) => <li key={lab.id} className="record-card"><div><strong>{lab.name}</strong><span className="status-tag">{lab.status === 1 ? t("common.active") : t("common.inactive")}</span></div><button className="button is-small" onClick={() => setEditingLab(lab)}>{t("admin.editLab")}</button></li>)}</ul></section>
    <section className="data-panel" aria-labelledby="conditions-title"><h2 id="conditions-title">{t("admin.conditions")}</h2><form onSubmit={submitCondition} className="workflow-form" key={editingCondition?.id ?? "new-condition"}><h3>{t(editingCondition ? "admin.editCondition" : "admin.createCondition")}</h3><label>{t("admin.lab")}<input name="conditionLabId" type="number" defaultValue={editingCondition?.labId ?? ""} required /></label><label>{t("admin.date")}<input name="conditionDate" type="date" defaultValue={editingCondition?.date ?? ""} required /></label><label>{t("admin.start")}<input name="conditionStart" type="time" defaultValue={editingCondition?.startTime ?? ""} required /></label><label>{t("admin.end")}<input name="conditionEnd" type="time" defaultValue={editingCondition?.endTime ?? ""} required /></label><label>{t("admin.type")}<input name="conditionType" defaultValue={editingCondition?.type ?? ""} required /></label><label>{t("admin.reason")}<textarea name="conditionReason" defaultValue={editingCondition?.reason ?? ""} required /></label>{editingCondition ? <label>{t("admin.status")}<select name="conditionStatus" defaultValue={editingCondition.status ?? 1}><option value="1">{t("common.active")}</option><option value="0">{t("common.inactive")}</option></select></label> : null}<div className="form-actions"><button className="button is-primary">{t(editingCondition ? "admin.saveCondition" : "admin.createCondition")}</button>{editingCondition ? <button type="button" className="button" onClick={() => setEditingCondition(null)}>{t("admin.cancelEdit")}</button> : null}</div></form><ul className="record-list">{data.conditions.map((condition) => <li key={condition.id} className="record-card"><div><strong>{condition.type}</strong><p>{condition.labName ?? field(condition, "UMG_Lab_Nombre")} · {condition.date} · {condition.startTime}–{condition.endTime}</p><p>{condition.reason}</p></div><button className="button is-small" onClick={() => setEditingCondition(condition)}>{t("admin.editCondition")}</button></li>)}</ul></section>
    <section className="data-panel" aria-labelledby="users-title"><h2 id="users-title">{t("admin.users")}</h2><form onSubmit={submitUser} className="workflow-form"><h3>{t("admin.createUser")}</h3><label>{t("admin.email")}<input name="username" type="email" required /></label><label>{t("admin.password")}<input name="password" type="password" required /></label><label>{t("admin.firstName")}<input name="firstName" required /></label><label>{t("admin.lastName")}<input name="lastName" required /></label><label>{t("admin.roleId")}<input name="roleId" type="number" required /></label><button className="button is-primary">{t("admin.createUser")}</button></form>{resettingUser ? <form onSubmit={submitReset} className="compact-form"><h3>{interpolate(t("admin.resetPasswordFor"), { email: resettingUser.email })}</h3><label>{t("admin.temporaryPassword")}<input name="temporaryPassword" type="password" required /></label><div className="form-actions"><button className="button is-primary">{t("admin.saveTemporaryPassword")}</button><button type="button" className="button" onClick={() => setResettingUser(null)}>{t("common.cancel")}</button></div></form> : null}<ul className="record-list">{data.users.map((user) => <li key={user.id} className="record-card"><div><strong>{user.name}</strong><p>{user.email} · {user.roleName ?? t("admin.noRole")}</p><span className="status-tag">{user.status === 1 ? t("common.active") : t("common.inactive")}</span></div><div className="record-actions"><button className="button is-small" onClick={() => setResettingUser(user)}>{t("admin.resetPassword")}</button><button className="button is-small is-danger is-light" disabled={user.status !== 1} onClick={() => { if (window.confirm(interpolate(t("admin.confirmDeactivate"), { email: user.email }))) run(() => createRenderApiClient().deactivateUser({ id: user.id }), "admin.userDeactivated"); }}>{t("admin.deactivateUser")}</button></div></li>)}</ul></section>
    <section className="data-panel" aria-labelledby="audit-title"><h2 id="audit-title">{t("admin.audit")}</h2><ul className="record-list">{data.logs.map((log) => <li key={log.id} className="record-card"><div><strong>{field(log, "umg_accion")}</strong><p>{field(log, "umg_modulo")} · {field(log, "umg_descripcion")}</p><p>{log.createdAt}</p></div></li>)}</ul>{data.logs.length === 0 ? <p role="status">{t("admin.noAudit")}</p> : null}</section>
  </section>;
}
